export const LOCATION = "G3TD3R_LOCATION";
export const NEGOTIATION = "G3TD3R_N3GOTIAT10N";
export const ACCESS_TOKEN = "G3TD3R_ACC3SS_T0K3N";
export const DRIVER = "G3TD3R_DR!V3R";
export const REGISTER_DRIVER = "G3TD3R_R!G3R_D!V3R";

export const TRIGGERS = {
  NEW_REQUEST: "NEW_REQUEST",
  NEGOTIATION_UPDATE: "NEGOTIATION_UPDATE",
};
